### PR TITLE
Kill Port and Restart When Unable to Hit NTP Server

### PR DESCRIPTION
**Pull request by jeffutter**
This 'works around' an bug I encountered when upgrading my Nerves system to 0.7. I can't if that actually caused the problem, but this fixes is.

What was happening is as follows:

Nerves_Ntp would start before my network was up. It would error with `ntpd: bad address` which were silently swallowed. After  my network came up: I would continue to get the `ntpd: bad address` errors. If I manually ran `start_link` the second process would work fine.

This change causes the ntpd process to be shut down and pause before restarting when `ntpd: bad address` errors occur. This fixes the problem I was seeing on nerves 0.7. I also can't imagine many real-world scenarios where you are unable to connect to a ntp server and killing, pausing, and restarting the process would cause problems.

### CODE REVIEW

**Comment by philipgiuliani** [comment]
This fix works fine for me on the nerves system 0.7. After killing the worker the first time, it syncs the time successfully.

**Comment by moperacz** [comment]
thank u for this, i will test this and merge 😉

**Comment by moperacz** [comment]
shit, forgot about it 😣

**Comment by philipgiuliani** [comment]
Thanks for merging it! :)

**Pull request merged**
